// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// select_line_connection_DeepState_TestHarness_generation.cpp and select_line_connection_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector select_line_connection(NumericVector p1, NumericVector b);

TEST(ggrepel_deepstate_test,select_line_connection_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector p1  = RcppDeepState_NumericVector();
  std::string p1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ggrepel/inst/testfiles/select_line_connection/AFL_select_line_connection/afl_inputs/" + std::to_string(t) + "_p1.qs";
  qs::c_qsave(p1,p1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p1 values: "<< p1 << std::endl;
  NumericVector b  = RcppDeepState_NumericVector();
  std::string b_t = "/home/akhila/fuzzer_packages/fuzzedpackages/ggrepel/inst/testfiles/select_line_connection/AFL_select_line_connection/afl_inputs/" + std::to_string(t) + "_b.qs";
  qs::c_qsave(b,b_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    select_line_connection(p1,b);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
