// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// IncomeTax_DeepState_TestHarness_generation.cpp and IncomeTax_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector IncomeTax(NumericVector x, NumericVector thresholds, NumericVector rates);

TEST(grattan_deepstate_test,IncomeTax_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/grattan/inst/testfiles/IncomeTax/AFL_IncomeTax/afl_inputs/" + std::to_string(t) + "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector thresholds  = RcppDeepState_NumericVector();
  std::string thresholds_t = "/home/akhila/fuzzer_packages/fuzzedpackages/grattan/inst/testfiles/IncomeTax/AFL_IncomeTax/afl_inputs/" + std::to_string(t) + "_thresholds.qs";
  qs::c_qsave(thresholds,thresholds_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "thresholds values: "<< thresholds << std::endl;
  NumericVector rates  = RcppDeepState_NumericVector();
  std::string rates_t = "/home/akhila/fuzzer_packages/fuzzedpackages/grattan/inst/testfiles/IncomeTax/AFL_IncomeTax/afl_inputs/" + std::to_string(t) + "_rates.qs";
  qs::c_qsave(rates,rates_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rates values: "<< rates << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    IncomeTax(x,thresholds,rates);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
