// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// libgdalcubes_set_threads_DeepState_TestHarness_generation.cpp and libgdalcubes_set_threads_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

void libgdalcubes_set_threads(IntegerVector n);

TEST(gdalcubes_deepstate_test,libgdalcubes_set_threads_test){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector n  = RcppDeepState_IntegerVector();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/gdalcubes/inst/testfiles/libgdalcubes_set_threads/AFL_libgdalcubes_set_threads/afl_inputs/" + std::to_string(t) + "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    libgdalcubes_set_threads(n);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
